// <auto-generated />
using System;
using Mayar.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mayar.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317133634_CategoryModel")]
    partial class CategoryModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Mayar.Api.Entities.BottomCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("MiddleCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleEnglish")
                        .HasColumnType("longtext");

                    b.Property<Guid>("TopCategoryId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("BottomCategories");
                });

            modelBuilder.Entity("Mayar.Api.Entities.HeroSlide", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ButtonLink")
                        .HasColumnType("longtext");

                    b.Property<string>("ButtonTextArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("ButtonTextEnglish")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("NewPrice")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("SubtitleArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("SubtitleEnglish")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleEnglish")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("HeroSlides");
                });

            modelBuilder.Entity("Mayar.Api.Entities.MiddleCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleEnglish")
                        .HasColumnType("longtext");

                    b.Property<Guid>("TopCategoryId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("MiddleCategories");
                });

            modelBuilder.Entity("Mayar.Api.Entities.TopCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ImageAlt")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleEnglish")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TopCategories");
                });

            modelBuilder.Entity("Mayar.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OtpCodeHash")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PinCode")
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
