// <auto-generated />
using System;
using Mayar.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mayar.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Mayar.Api.Entities.BottomCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("MiddleCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleEnglish")
                        .HasColumnType("longtext");

                    b.Property<Guid>("TopCategoryId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("BottomCategories");
                });

            modelBuilder.Entity("Mayar.Api.Entities.HeroSlide", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ButtonLink")
                        .HasColumnType("longtext");

                    b.Property<string>("ButtonTextArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("ButtonTextEnglish")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("NewPrice")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("SubtitleArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("SubtitleEnglish")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleEnglish")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("HeroSlides");
                });

            modelBuilder.Entity("Mayar.Api.Entities.MiddleCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ButtonLink")
                        .HasColumnType("longtext");

                    b.Property<string>("ButtonTextArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("ButtonTextEnglish")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageAlt")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("SubtitleArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("SubtitleEnglish")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleEnglish")
                        .HasColumnType("longtext");

                    b.Property<Guid>("TopCategoryId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("MiddleCategories");
                });

            modelBuilder.Entity("Mayar.Api.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("BasePrice")
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid?>("BottomCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("BrandArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("BrandEnglish")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("CompareAtPrice")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("FullDescriptionArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("FullDescriptionEnglish")
                        .HasColumnType("longtext");

                    b.Property<bool>("InStock")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsBestSeller")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsNew")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsOnSale")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("MiddleCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NameArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("NameEnglish")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(18,1)");

                    b.Property<string>("ReturnInfoArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("ReturnInfoEnglish")
                        .HasColumnType("longtext");

                    b.Property<int?>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("ShippingInfoArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingInfoEnglish")
                        .HasColumnType("longtext");

                    b.Property<string>("ShortDescriptionArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("ShortDescriptionEnglish")
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<Guid>("TopCategoryId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductCareInstruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("InstructionArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("InstructionEnglish")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCareInstructions");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Hex")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NameArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("NameEnglish")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductColors");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ImageAlt")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LabelArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("LabelEnglish")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductFeatures");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ImageAlt")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductSize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSizes");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductSpecification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LabelArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("LabelEnglish")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ValueArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("ValueEnglish")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSpecifications");
                });

            modelBuilder.Entity("Mayar.Api.Entities.TopCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ImageAlt")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleEnglish")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TopCategories");
                });

            modelBuilder.Entity("Mayar.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("PinCode")
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Mayar.Api.Entities.Wishlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductCareInstruction", b =>
                {
                    b.HasOne("Mayar.Api.Entities.Product", "Product")
                        .WithMany("CareInstructions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductColor", b =>
                {
                    b.HasOne("Mayar.Api.Entities.Product", "Product")
                        .WithMany("Colors")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductFeature", b =>
                {
                    b.HasOne("Mayar.Api.Entities.Product", "Product")
                        .WithMany("Features")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductImage", b =>
                {
                    b.HasOne("Mayar.Api.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductSize", b =>
                {
                    b.HasOne("Mayar.Api.Entities.Product", "Product")
                        .WithMany("Sizes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductSpecification", b =>
                {
                    b.HasOne("Mayar.Api.Entities.Product", "Product")
                        .WithMany("Specifications")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mayar.Api.Entities.Product", b =>
                {
                    b.Navigation("CareInstructions");

                    b.Navigation("Colors");

                    b.Navigation("Features");

                    b.Navigation("Images");

                    b.Navigation("Sizes");

                    b.Navigation("Specifications");
                });
#pragma warning restore 612, 618
        }
    }
}
